insert into comments (ID, COMMENTED_BY, COMMENTED_ON, DESCRIPTION, IS_PRIVATE, UPVOTES, DOWNVOTES, PARENT_ID)
values (1,2,1,"You are great, my lord", false, 3,0,NULL),
(2,4,1,"I'm sure you're gonna be famous bro", false, 5,0, NULL),
(3,5,1,"We have just two words for you -> The Best", false, 2,0, NULL),
(4,4,1,"I'm sure you're gonna be famous bro", false, 5,0, NULL),
(5,5,1,"We have just two words for you -> The Best", false, 2,0, NULL),
(6,4,1,"I'm sure you're gonna be famous bro", false, 5,0, NULL),
(7,5,1,"We have just two words for you -> The Best", false, 2,0, NULL),
(8,4,1,"I'm sure you're gonna be famous bro", false, 5,0, NULL),
(9,5,1,"We have just two words for you -> The Best", false, 2,0, NULL),
(10,4,1,"I'm sure you're gonna be famous bro", false, 5,0, NULL),
(11,5,1,"We have just two words for you -> The Best", false, 2,0, NULL),
(12,4,1,"I'm sure you're gonna be famous bro", false, 5,0, NULL),
(13,5,1,"We have just two words for you -> The Best", false, 2,0, NULL),
(14,1,4,"Tum se na ho payega", false, 100,1, NULL);